version: 2
workflows:
  version: 2
  default:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - deploy:
          requires:
            - build
jobs:
  prepare:
    docker:
      - image: circleci/ruby:2.3-node
    environment:
      - YARN_CACHE_FOLDER: ~/yarn_cache
    steps:
      # Machine Setup
      - checkout
      # Dependencies
      - restore_cache:
          keys:
          - v1-dep-{{ .Branch }}-
          - v1-dep-editing-
          - v1-dep-
      # Install npm and bundle dependencies
      - run: npm config set prefix ~ && npm install -g yarn
      - run: ~/bin/yarn
      - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
          --jobs=4 --retry=3 '
      # Save dependency cache
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
          - vendor/bundle
          - ~/.bundle
          - ./node_modules
          - ~/yarn_cache
  build:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dep-{{ .Branch }}-
          - v1-dep-editing-
          - v1-dep-
      - run: ls
      - run: ./ci.sh
      - store_artifacts:
          path: _site/pdf
      - store_artifacts:
          path: _site/books
      - persist_to_workspace:
          root: ~/project
          paths:
            - _site
  deploy:
    docker:
      - image: circleci/ruby:2.3-node
    steps:
      - attach_workspace:
          at: ~/project
      - run: ./tools/deploy.sh
